import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Inter, Poppins} from 'next/font/google'
import Chakra from "@/Providers/Chakra";
import Navbar from "@/components/main/Navbar";
import { Box } from "@chakra-ui/react";
import Sidebar from "@/components/main/Sidebar";
import SidebarWrapper from "@/components/main/SidebarWrapper";
import GlobalVariableContext from "@/contexts/GlobalVariableContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter=Inter({subsets:['latin']})
const poppins=Poppins({subsets:['latin'],weight:['100','200','300','400','500','600','800','900']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className}`}>
        <Chakra>
          <Box mt={'100px'}>
            <Navbar/>
            <GlobalVariableContext>
              <SidebarWrapper>
                {children}
              </SidebarWrapper>
            </GlobalVariableContext>
          </Box>
        </Chakra>
      </body>
    </html>
  );
}
